version: "3.8"

services:
  postgres_db:
    image: postgres:16
    container_name: greenandcoop_postgres
    environment: # variables d'environnement
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - volume_postgre:/var/lib/postgresql/data

volumes:
  volume_postgre:

