version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo_db

    ports:
      - "27018:27017"   # Expose MongoDB sur le port 27018 de l’hôte

    volumes:
      - mongo_data:/data/db   # Volume persistant pour conserver les données MongoDB

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}   # Nom d’utilisateur root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}   # Mot de passe root

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]   # Vérifie que Mongo répond
      interval: 5s     # Intervalle entre les checks
      timeout: 5s      # Timeout d’un check
      retries: 10      # Nombre de tentatives avant échec

    networks:
      - data_pipeline_network   # Réseau Docker partagé

  migration:
    build: .   # Build l’image Docker à partir du Dockerfile local
    container_name: migration_script

    depends_on:
      mongo:
        condition: service_healthy   # Attend que Mongo soit prêt avant d’exécuter le script

    volumes:
      - ./healthcare_dataset:/app/data   # Monte le dossier contenant les CSV

    environment:
      - MONGO_URI=${MONGO_URI}   # URI MongoDB injectée depuis .env
      - CSV_PATH=/app/data       # Chemin des fichiers CSV dans le conteneur

    networks:
      - data_pipeline_network

volumes:
  mongo_data:   # Volume persistant pour MongoDB

networks:
  data_pipeline_network:
    driver: bridge   # Réseau Docker en mode bridge
