version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo_db

    ports:
      - "27018:27017"   # Expose MongoDB sur le port 27018 de l’hôte

    volumes:
      - mongo_data:/data/db   # Volume persistant pour conserver les données MongoDB

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - data_pipeline_network

  migration:
    build: .
    container_name: migration_script

    depends_on:
      mongo:
        condition: service_healthy

    volumes:
      - ./healthcare_dataset:/app/data

    environment:
      - MONGO_URI=${MONGO_URI}
      - CSV_PATH=/app/data

    networks:
      - data_pipeline_network

volumes:
  mongo_data:

networks:
  data_pipeline_network:
    driver: bridge
