sport_data_solution:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DATA_DB_HOST', 'localhost') }}"
      port: "{{ env_var('DATA_DB_PORT', '5433') | as_number }}"
      user: "{{ env_var('DATA_DB_USER', 'sds_admin') }}"
      password: "{{ env_var('DATA_DB_PASSWORD') }}"
      dbname: "{{ env_var('DATA_DB_NAME', 'sport_data') }}"
      schema: public
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
